---
title: ' Data Management Plan'
teaching: 0
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- None

::::::::::::::::::::::::::::::::::::::::::::::::


::: objectives
-   Establishing a data management strategy within the CRC.
-   Detailing roles and responsibilities for data management.
:::

## Overview


The data generated in high-throughput experiments can be categorized into two main types:

**Unprocessed (or raw) data** refers to the unprocessed data directly obtained from high-throughput experiments. This includes the output from sequencing machines. The data management team will establish protocols for the collection, storage, and initial processing of raw data to ensure its integrity and reliability. There is a general rule of thumb for 

**Processed data** represents the results obtained after applying various bioinformatics and statistical analysis techniques to the raw data. This includes sequences filtered by quality, identified genetic variants, and derived annotations, such as genes called differentially expressed. The data management team will work closely with the bioinformatics team to establish workflows and standardize processing methods to ensure consistent and reproducible results.

